---
title: "Interpolación de modelos"
author: "Pizarro, P., Castro, S. y Insunza, D."
date: "18-01-2021"
output: 
  bookdown::html_document2:
    figure_caption: true
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(raster)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(broom)
library(sp)
library(rworldxtra)
library(gstat)
library(rgdal)
library(ggspatial)
library(rlang)

```

```{r}
Diversidad <- read_sf("Diversidad.shp")

Stack <- read_rds("Stack.rds")
```

```{r}
Chile <- getData("GADM", country = "CHL", level = 1) %>%  st_as_sf() %>%  dplyr::filter(NAME_1 %in% c("Los Ríos", "Los Lagos", "Araucanía")) %>% st_make_valid()

ggplot() + 
  geom_sf(data = Chile) + 
  geom_sf(data = Diversidad, aes(color = DvrsddA)) +
  scale_color_viridis_c(name = "Riqueza de especies") +
  theme_bw()
```

```{r}
plot(Stack)
```


```{r}
Variables_DF = Stack %>% raster::extract(Diversidad) %>% as.data.frame()
Diversidad_2 = bind_cols(Diversidad, Variables_DF)
Diver_2 = Diversidad_2 %>% as_Spatial()

NewVars_DF <-  Stack %>% as("SpatialPixelsDataFrame") %>% as.data.frame() %>% st_as_sf(coords = c(6,7), crs = "+proj=longlat +datum=WGS84 +no_defs") %>%  as_Spatial()

```

```{r}
#modelo 1
Z_vgm_null <- variogram(log(DvrsddA) ~ 1 , data = Diver_2) %>% mutate(Modelo = "Nulo")

#modelo 2
Z_vgm_spatial <- variogram(log(DvrsddA) ~ coords.x1 + coords.x2 , data = Diver_2) %>% mutate(Modelo = "Espacial")

#modelo 3
Z_vgm_interaccion1 <- variogram(log(DvrsddA) ~ ModificacionHumana + I(ModificacionHumana^2) + TempMedia + I(TempMedia^2) + RangoTempDiario + I(RangoTempDiario^2) + PrecAnual + I(PrecAnual^2) + PrecAnual + I(PrecAnual^2) + EstacionalidadPrec + I(EstacionalidadPrec^2), data = Diver_2) %>% mutate(Modelo = "Interacción1")

#modelo 4
Z_vgm_interaccion2 <- variogram(log(DvrsddA) ~ TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec +  I((ModificacionHumana)^2) + I((TempMedia)^2) + RangoTempDiario + I((RangoTempDiario)^2) + EstacionalidadPrec + I((EstacionalidadPrec)^2), data = Diver_2) %>% mutate(Modelo = "Interacción2")

#modelo 5
Z_vgm_mixto <- variogram(log(DvrsddA) ~ (coords.x1 + coords.x2) + TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec, data = Diver_2) %>% mutate(Modelo = "Mixto")

#modelo 6
Z_vgm_mixto2 <- variogram(log(DvrsddA) ~ (coords.x1 + coords.x2) + ModificacionHumana + I(ModificacionHumana^2), data = Diver_2) %>% mutate(Modelo = "Mixto2")
```


```{r}
Z_vgm <- rbind(Z_vgm_null, Z_vgm_spatial, Z_vgm_interaccion1, Z_vgm_interaccion2, Z_vgm_mixto, Z_vgm_mixto2)


ggplot(Z_vgm, aes(x = dist, y = gamma, color = Modelo)) + 
  geom_smooth() + 
  geom_point() +
  theme_bw() + scale_fill_viridis_c()
  
```

```{r}

Abn_fit_null <- fit.variogram(Z_vgm_null, model = vgm(1, "Sph", 700, 1))

Abn_fit_Spat <- fit.variogram(Z_vgm_spatial, model = vgm(1, "Sph", 700, 1))

Abn_fit_Interaccion1 <- fit.variogram(Z_vgm_interaccion1, model = vgm(1, "Sph", 700, 1))

Abn_fit_Interaccion2 <- fit.variogram(Z_vgm_interaccion2, model = vgm(1, "Sph", 700, 1))

Abn_fit_Mixto <- fit.variogram(Z_vgm_mixto, model = vgm(1, "Sph", 700, 1))

Abn_fit_Mixto2 <- fit.variogram(Z_vgm_mixto2, model = vgm(1, "Sph", 700, 1))
```

```{r}

ggplot(Z_vgm_null, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 0.05698552, lty = 2) + geom_vline(xintercept = 80.19058, lty = 2) + theme_bw()

ggplot(Z_vgm_spatial, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 0.05458574, lty = 2) + geom_vline(xintercept = 75.58536, lty = 2) + theme_bw()

ggplot(Z_vgm_interaccion1, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 0.03680731, lty = 2) + geom_vline(xintercept = 62.5634, lty = 2) + theme_bw()

ggplot(Z_vgm_interaccion2, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 4.196248e-05 + 3.370992e-02, lty = 2) + geom_vline(xintercept = 61.50199, lty = 2) + theme_bw()

ggplot(Z_vgm_mixto, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 0.03413205, lty = 2) + geom_vline(xintercept = 61.85772, lty = 2) + theme_bw()

ggplot(Z_vgm_mixto2, aes(x = dist, y = gamma, color = Modelo)) + geom_point() + geom_hline(yintercept = 0.04281398, lty = 2) + geom_vline(xintercept = 69.32882, lty = 2) + theme_bw()
```

```{r}
Null_pred <- krige(log(DvrsddA) ~ 1, Diver_2, NewVars_DF, model = Abn_fit_null) %>% st_as_sf() %>% mutate(Modelo = "Nulo")
  
#Resultado
ggplot() + 
  geom_sf(data = Null_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Modelo Nulo") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Null_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza") + labs(title = "Predicciones Modelo Nulo") + theme_bw()

```
```{r}

Spat_pred <- krige(log(DvrsddA) ~ coords.x1 + coords.x2, Diver_2, NewVars_DF, model = Abn_fit_Spat) %>% st_as_sf(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Modelo = "Espacial")


#Resultado
ggplot() + 
  geom_sf(data = Spat_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Modelo Espacial") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Spat_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza")+ labs(title = "Predicciones Modelo Espacial") + theme_bw()

```


```{r}
Interaccion1_pred <- krige(log(DvrsddA) ~ ModificacionHumana + I(ModificacionHumana^2) + TempMedia + I(TempMedia^2) + RangoTempDiario + I(RangoTempDiario^2) + PrecAnual + I(PrecAnual^2) + PrecAnual + I(PrecAnual^2) + EstacionalidadPrec + I(EstacionalidadPrec^2), Diver_2, NewVars_DF, model = Abn_fit_Interaccion1) %>% st_as_sf() %>%  mutate(Modelo = "Interacción1")

#Resultado
ggplot() + 
  geom_sf(data = Interaccion1_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Modelo Interacción") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Interaccion1_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza") + labs(title = "Predicciones Modelo Interacción1") + theme_bw()

```

```{r}
Interaccion2_pred <- krige(log(DvrsddA) ~ TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec +  I((ModificacionHumana)^2) + I((TempMedia)^2) + RangoTempDiario + I((RangoTempDiario)^2) + EstacionalidadPrec + I((EstacionalidadPrec)^2), Diver_2, NewVars_DF, model = Abn_fit_Interaccion2) %>% st_as_sf() %>%  mutate(Modelo = "Interacción2")

#Resultado
ggplot() + 
  geom_sf(data = Interaccion2_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Modelo Interacción2") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Interaccion2_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza") + labs(title = "Predicciones Modelo Interacción2") + theme_bw()


```
```{r}
Mixto_pred <- krige(log(DvrsddA) ~ coords.x1 + coords.x2 + TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec, Diver_2, NewVars_DF, model = Abn_fit_Interaccion2) %>% st_as_sf() %>%  mutate(Modelo = "Mixto")

#Resultado
ggplot() + 
  geom_sf(data = Mixto_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Mixto") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Mixto_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza") + labs(title = "Predicciones Modelo Mixto") + theme_bw()

```
```{r}
Mixto2_pred <- krige(log(DvrsddA) ~ coords.x1 + coords.x2 +  ModificacionHumana + I(ModificacionHumana^2), Diver_2, NewVars_DF, model = Abn_fit_Interaccion2) %>% st_as_sf() %>%  mutate(Modelo = "Mixto2")

#Resultado
ggplot() + 
  geom_sf(data = Mixto2_pred, aes(color = exp(var1.pred))) + 
  scale_color_viridis_c(name= "Diversidad") + labs(title = "Predicciones Mixto") + theme_bw()

#Varianza
ggplot() + 
  geom_sf(data = Mixto2_pred, aes(color = var1.var)) + 
  scale_color_viridis_c(name= "Varianza") + labs(title = "Predicciones Modelo Mixto") + theme_bw()

```



```{r}
Pred <- list(Null_pred, Spat_pred, Interaccion1_pred, Interaccion2_pred, Mixto_pred, Mixto2_pred) %>% reduce(bind_rows)

ggplot() + geom_sf(data = Pred, aes(color = exp(var1.pred))) + scale_color_viridis_c(name= "Diversidad de especies de aves") +  facet_wrap(~ Modelo) +  theme_bw() + theme(axis.text.x = element_text(angle =90, vjust = 0.5, hjust=1))

ggplot() + geom_sf(data = Pred, aes(color = exp(var1.var))) + scale_color_viridis_c(name= "Varianza") +  facet_wrap(~ Modelo) +  theme_bw() + theme(axis.text.x = element_text(angle =90, vjust = 0.5, hjust=1))

```

```{r}
Null_CV <- krige.cv(log(DvrsddA) ~ 1, Diver_2, model = Abn_fit_null, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Nulo")

Spat_CV <- krige.cv(log(DvrsddA) ~ coords.x1 + coords.x2, Diver_2, model = Abn_fit_Spat, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Espacial")

Interaccion1_CV <- krige.cv(log(DvrsddA) ~ ModificacionHumana + I(ModificacionHumana^2) + TempMedia + I(TempMedia^2) + RangoTempDiario + I(RangoTempDiario^2) + PrecAnual + I(PrecAnual^2) + PrecAnual + I(PrecAnual^2) + EstacionalidadPrec + I(EstacionalidadPrec^2), Diver_2, model = Abn_fit_Interaccion1, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Interacción1")

Interaccion2_CV <- krige.cv(log(DvrsddA) ~ TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec +  I((ModificacionHumana)^2) + I((TempMedia)^2) + RangoTempDiario + I((RangoTempDiario)^2) + EstacionalidadPrec + I((EstacionalidadPrec)^2), Diver_2, model = Abn_fit_Interaccion2, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Interacción2")

Mixto_CV <- krige.cv(log(DvrsddA) ~ coords.x1 + coords.x2 + TempMedia*(RangoTempDiario*ModificacionHumana)*EstacionalidadPrec, Diver_2, model = Abn_fit_Mixto, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Mixto")

Mixto2_CV <- krige.cv(log(DvrsddA) ~ coords.x1 + coords.x2 + ModificacionHumana + I(ModificacionHumana^2), Diver_2, model = Abn_fit_Mixto2, nfold = 5) %>% st_as_sf() %>% mutate(Modelo = "Mixto2")

Pred_CV <- list(Null_CV, Spat_CV, Interaccion1_CV, Interaccion2_CV, Mixto_CV, Mixto2_CV) %>% reduce(bind_rows)
```

```{r}

Resumen <- Pred_CV %>% as.data.frame() %>% group_by(Modelo) %>% 
  summarise(RMSE = sqrt(sum(residual^2)/length(residual))) %>% 
  arrange(RMSE)

kable(Resumen, caption = "Tabla resumen modelos") %>% 
kable_styling(position = "center")
```


